### PR TITLE
Feature/video support

### PR DESCRIPTION
**Pull request by tonyraoul**
# Adding basic Video Support

- Support mp4 extension only at the moment

- Videos are on Loop and muted will add control soon

- Working on all major browsers for Desktop/Mobile

### CODE REVIEW

**Comment by phegman** [comment]
Hi Tony,

I no longer have time to maintain this project, would you be interested in becoming a maintainer of this project?

**Comment by tonyraoul** [comment]
Thanks Peter,
that would be great.
It would be my honor, my company is using this plugin for a while, big thanks for contributors.

**Comment by phegman** [comment]
Great! I just added you as a collaborator to the repo. This should allow you to merge PRs and push to the repo. I am not sure how to transfer the plugin on the October CMS site. Do you know how?

**Comment by tonyraoul** [comment]
No need to do so, Octobercms pulls the latest version from github if the method of upload is Git.
Thanks again,

**Comment by fbrzozowski** [comment]
Any plans on merging this PR? :)

**Comment by tonyraoul** [comment]
@fbrzozowski sorry totally missed your message from earlier, any need to merge this ? I was planning to either archive this project or start maintaining it again if there is any usage.

**Pull request closed without merging**
